[package]
name = "kv-db"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
log = "0.4"
env_logger = "0.10"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
